// <auto-generated />
using System;
using Equipment.M;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Equipment.Migrations.Entity
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("OKB3Admin.M.Korpus_M", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("PodrazdelenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PodrazdelenieId");

                    b.ToTable("Korpus");
                });

            modelBuilder.Entity("OKB3Admin.M.Otdelenie_M", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Blok")
                        .HasColumnType("longtext");

                    b.Property<string>("Coment")
                        .HasColumnType("longtext");

                    b.Property<string>("Etag")
                        .HasColumnType("longtext");

                    b.Property<int?>("KorpusId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nuber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("KorpusId");

                    b.ToTable("Otdelenie");
                });

            modelBuilder.Entity("OKB3Admin.M.Podrazdelenie_M", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Coment")
                        .HasColumnType("longtext");

                    b.Property<string>("Dom")
                        .HasColumnType("longtext");

                    b.Property<string>("Gorod")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PostIndex")
                        .HasColumnType("longtext");

                    b.Property<string>("Psevdonim")
                        .HasColumnType("longtext");

                    b.Property<string>("Ulica")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Podrazdelenies");
                });

            modelBuilder.Entity("OKB3Admin.M.Server_M", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("NetName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Server_M");
                });

            modelBuilder.Entity("OKB3Admin.M.Sotrudnik_M", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MainTabelNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Patron")
                        .HasColumnType("longtext");

                    b.Property<string>("Snils")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sur")
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sotrudnik_M");
                });

            modelBuilder.Entity("OKB3Admin.M.Telefon_M", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Blok")
                        .HasColumnType("longtext");

                    b.Property<string>("Coment")
                        .HasColumnType("longtext");

                    b.Property<string>("Etag")
                        .HasColumnType("longtext");

                    b.Property<string>("Kabel")
                        .HasColumnType("longtext");

                    b.Property<string>("Kabinet")
                        .HasColumnType("longtext");

                    b.Property<string>("KontaktName")
                        .HasColumnType("longtext");

                    b.Property<string>("MacAdress")
                        .HasColumnType("longtext");

                    b.Property<string>("Magistral")
                        .HasColumnType("longtext");

                    b.Property<string>("OborudovanieName")
                        .HasColumnType("longtext");

                    b.Property<int?>("OtdelenieId")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .HasColumnType("longtext");

                    b.Property<string>("Raspredelenie")
                        .HasColumnType("longtext");

                    b.Property<int?>("ServerId")
                        .HasColumnType("int");

                    b.Property<int?>("SotrudnikId")
                        .HasColumnType("int");

                    b.Property<string>("TelefonDop")
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonLineNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonMain")
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonVnut")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OtdelenieId");

                    b.HasIndex("ServerId");

                    b.HasIndex("SotrudnikId");

                    b.ToTable("Telefon_M");
                });

            modelBuilder.Entity("OKB3Admin.M.Users_M", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("Dostup")
                        .HasColumnType("longblob");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Pass")
                        .HasColumnType("longblob");

                    b.Property<int>("SotridnikId")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SotridnikId");

                    b.ToTable("Users_M");
                });

            modelBuilder.Entity("OKB3Admin.M.Korpus_M", b =>
                {
                    b.HasOne("OKB3Admin.M.Podrazdelenie_M", "Podrazdelenie")
                        .WithMany("Korpus_Ms")
                        .HasForeignKey("PodrazdelenieId");

                    b.Navigation("Podrazdelenie");
                });

            modelBuilder.Entity("OKB3Admin.M.Otdelenie_M", b =>
                {
                    b.HasOne("OKB3Admin.M.Korpus_M", "Korpus")
                        .WithMany("Otdelenie_Ms")
                        .HasForeignKey("KorpusId");

                    b.Navigation("Korpus");
                });

            modelBuilder.Entity("OKB3Admin.M.Sotrudnik_M", b =>
                {
                    b.HasOne("OKB3Admin.M.Users_M", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OKB3Admin.M.Telefon_M", b =>
                {
                    b.HasOne("OKB3Admin.M.Otdelenie_M", "Otdelenie")
                        .WithMany("Telefon_Ms")
                        .HasForeignKey("OtdelenieId");

                    b.HasOne("OKB3Admin.M.Server_M", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId");

                    b.HasOne("OKB3Admin.M.Sotrudnik_M", "Sotrudnik")
                        .WithMany("Telefons")
                        .HasForeignKey("SotrudnikId");

                    b.Navigation("Otdelenie");

                    b.Navigation("Server");

                    b.Navigation("Sotrudnik");
                });

            modelBuilder.Entity("OKB3Admin.M.Users_M", b =>
                {
                    b.HasOne("OKB3Admin.M.Sotrudnik_M", "Sotrudnik")
                        .WithMany()
                        .HasForeignKey("SotridnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sotrudnik");
                });

            modelBuilder.Entity("OKB3Admin.M.Korpus_M", b =>
                {
                    b.Navigation("Otdelenie_Ms");
                });

            modelBuilder.Entity("OKB3Admin.M.Otdelenie_M", b =>
                {
                    b.Navigation("Telefon_Ms");
                });

            modelBuilder.Entity("OKB3Admin.M.Podrazdelenie_M", b =>
                {
                    b.Navigation("Korpus_Ms");
                });

            modelBuilder.Entity("OKB3Admin.M.Sotrudnik_M", b =>
                {
                    b.Navigation("Telefons");
                });
#pragma warning restore 612, 618
        }
    }
}
